
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lazar
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonBacardi = new javax.swing.JRadioButton();
        jRadioButtonHavana = new javax.swing.JRadioButton();
        jRadioButtonBambu = new javax.swing.JRadioButton();
        jCheckBoxEXP = new javax.swing.JCheckBox();
        jSpinnerDJ4 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jRadioButtonDonJulio = new javax.swing.JRadioButton();
        jRadioButtonVodka = new javax.swing.JRadioButton();
        jRadioButtonHennessy = new javax.swing.JRadioButton();
        jSpinnerTH6 = new javax.swing.JSpinner();
        jSpinnerVS5 = new javax.swing.JSpinner();
        jSpinnerBR1 = new javax.swing.JSpinner();
        jSpinnerHC2 = new javax.swing.JSpinner();
        jSpinnerBam3 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jRadioButtonModelo6 = new javax.swing.JRadioButton();
        jRadioButtonCorona6 = new javax.swing.JRadioButton();
        jRadioButtonHeineken6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonCorona1 = new javax.swing.JRadioButton();
        jRadioButtonModelo1 = new javax.swing.JRadioButton();
        jRadioButtonHeineken1 = new javax.swing.JRadioButton();
        jSpinnerCorona6 = new javax.swing.JSpinner();
        jSpinnerModelo6 = new javax.swing.JSpinner();
        jSpinnerHeineken6 = new javax.swing.JSpinner();
        jSpinnerCorona1 = new javax.swing.JSpinner();
        jSpinnerModelo1 = new javax.swing.JSpinner();
        jSpinnerHeineken1 = new javax.swing.JSpinner();
        jTextFieldTip = new javax.swing.JTextField();
        jCheckBoxTip = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Lazar's Liquor Online Shop");

        jLabel2.setText("Enter Name: ");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Adress: ");

        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Liquor:");

        jRadioButtonBacardi.setText("Bacardi Rum - $15");
        jRadioButtonBacardi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBacardiActionPerformed(evt);
            }
        });

        jRadioButtonHavana.setText("Rum Havana Club - $20");
        jRadioButtonHavana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHavanaActionPerformed(evt);
            }
        });

        jRadioButtonBambu.setText("Bambu Rum - $25");
        jRadioButtonBambu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBambuActionPerformed(evt);
            }
        });

        jCheckBoxEXP.setText("Express Delivery - $5");
        jCheckBoxEXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEXPActionPerformed(evt);
            }
        });

        jButton1.setText("Process Transaction With Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rum boytle.png"))); // NOI18N

        jRadioButtonDonJulio.setText("Tequila(Don Julio) - $32");
        jRadioButtonDonJulio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDonJulioActionPerformed(evt);
            }
        });

        jRadioButtonVodka.setText("Vodka Sky - $35");
        jRadioButtonVodka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVodkaActionPerformed(evt);
            }
        });

        jRadioButtonHennessy.setText("Tequila Hennessy - $37");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Beers:");

        jRadioButtonModelo6.setText("Modelo - $19");

        jRadioButtonCorona6.setText("Corona - $16");

        jRadioButtonHeineken6.setText("Heineken - $23");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("6 packs:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Single:");

        jRadioButtonCorona1.setText("Corona - $3");

        jRadioButtonModelo1.setText("Modelo - 4$");

        jRadioButtonHeineken1.setText("Heineken $6");

        jCheckBoxTip.setText("Tip?   ");

        jLabel8.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonBambu)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinnerBam3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jRadioButtonBacardi)
                                    .addGap(27, 27, 27)
                                    .addComponent(jSpinnerBR1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonHavana)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerHC2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDonJulio)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonVodka)
                                    .addComponent(jRadioButtonHennessy))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerDJ4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerTH6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jSpinnerVS5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel5)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonCorona6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerCorona6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonModelo6)
                                    .addComponent(jRadioButtonHeineken6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerHeineken6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerModelo6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonHeineken1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonCorona1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerCorona1)
                            .addComponent(jSpinnerModelo1)
                            .addComponent(jSpinnerHeineken1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(126, 126, 126))))
            .addGroup(layout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxEXP)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxTip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTip, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(131, 131, 131)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxEXP)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jSpinnerBR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonBacardi)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonHavana)
                                    .addComponent(jSpinnerHC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonBambu)
                                    .addComponent(jSpinnerBam3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonDonJulio)
                                    .addComponent(jSpinnerDJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonVodka)
                                    .addComponent(jSpinnerVS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonHennessy)
                                    .addComponent(jSpinnerTH6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxTip)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel6)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(35, 35, 35)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonCorona6)
                                            .addComponent(jSpinnerCorona6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonModelo6)
                                            .addComponent(jSpinnerModelo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonHeineken6)
                                            .addComponent(jSpinnerHeineken6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonCorona1)
                                            .addComponent(jSpinnerCorona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonModelo1)
                                            .addComponent(jSpinnerModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jRadioButtonHeineken1)
                                            .addComponent(jSpinnerHeineken1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12))))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jRadioButtonBambuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBambuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBambuActionPerformed

    private void jRadioButtonHavanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHavanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonHavanaActionPerformed
   int totalPrice;
    int finalPrice;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           int p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12;
           int tip = Integer.parseInt(jTextFieldTip.getText());
        String n = jTextFieldName.getText();
       String a = jTextFieldAddress.getText();
       String type = "";
       int q1 = (Integer) jSpinnerBR1.getValue();
       int q2 = (Integer) jSpinnerHC2.getValue();
       int q3 = (Integer) jSpinnerBam3.getValue();
       int q4 = (Integer) jSpinnerDJ4.getValue();
       int q5 = (Integer) jSpinnerVS5.getValue();
       int q6 = (Integer) jSpinnerTH6.getValue();
       int q7 = (Integer) jSpinnerCorona6.getValue();
       int q8 = (Integer) jSpinnerModelo6.getValue();
       int q9 = (Integer) jSpinnerHeineken6.getValue();
       int q10 = (Integer) jSpinnerCorona1.getValue();
       int q11 = (Integer) jSpinnerModelo1.getValue();
       int q12 = (Integer) jSpinnerHeineken1.getValue();
       
        if(jRadioButtonBacardi.isSelected()){
            totalPrice = 15 * q1;  
            //type = "Bacardi Rum";
           
          }
         p1 = totalPrice;
        if(jRadioButtonHavana.isSelected()){
            totalPrice = p1 + 20 * q2;
            //type = "Havana Club";
        } 
        p2 = totalPrice;
        
        if(jRadioButtonBambu.isSelected()){
            totalPrice = p2 + 25 * q3;
            
        }
        p3 = totalPrice;
        if(jRadioButtonDonJulio.isSelected()){
            totalPrice = p3 +32 * q4;
        } 
        p4 = totalPrice;
        if(jRadioButtonVodka.isSelected()){
            totalPrice = p4 + 35 * q5; 
        } 
        p5 = totalPrice;
        if(jRadioButtonHennessy.isSelected()){
            totalPrice = p5 + 37 * q6;
        }
        p6 = totalPrice;
        
        if(jRadioButtonCorona6.isSelected()){
            totalPrice = p6 + 16 * q7;
        }
        p7 = totalPrice;
          if(jRadioButtonModelo6.isSelected()){
              totalPrice = p7 + 19 * q8;
          }
          p8 = totalPrice;
          if(jRadioButtonHeineken6.isSelected()){
              totalPrice = p8 + 23 * q9;
          }
          p9 = totalPrice;
          if(jRadioButtonCorona1.isSelected()){
              totalPrice = p9 + 3 * q10;
          }
          p10 = totalPrice;
          if(jRadioButtonModelo1.isSelected()){
              totalPrice = p10 + 4 * q11;
          }
          p11 = totalPrice;
          if(jRadioButtonHeineken1.isSelected()){
              totalPrice = p11 + 6 * q12;
          }
          
        
        finalPrice = totalPrice;
       if(jCheckBoxEXP.isSelected()){
           finalPrice = finalPrice + 5;
       }
       if(jCheckBoxTip.isSelected()){
           finalPrice = finalPrice + tip;
       }
       JOptionPane.showMessageDialog(this, "Transaction Successful, your total is $" + finalPrice + "\n" + n + " your order will be delivered to " + a); //+ //"\n" + "You ordered " + q + " bottles of " + type + " to be delivered to " + a );
       
    //try {
     // FileWriter myWriter = new FileWriter("data.txt");
     // myWriter.write("Name: " + n + " Adress: " + a + ", ordered " + q + " bottles of " + type + ", the total price is $" + finalPrice);
     // myWriter.close();
     // JOptionPane.showMessageDialog(this, "Transaction Successful, your total is $" + finalPrice);
    //} catch (IOException e) {
    //  System.out.println("An error occurred.");
    //}  
    jTextFieldName.setText("");
    jTextFieldAddress.setText("");
    jTextFieldTip.setText("");
    jSpinnerBR1.setValue(0);
    jSpinnerHC2.setValue(0);
    jSpinnerBam3.setValue(0);
    jSpinnerDJ4.setValue(0);
    jSpinnerVS5.setValue(0);
   jSpinnerTH6.setValue(0);
   jSpinnerModelo6.setValue(0);
    jSpinnerCorona6.setValue(0);
    jSpinnerHeineken6.setValue(0);
    jSpinnerHeineken1.setValue(0);
    jSpinnerCorona1.setValue(0);
   jSpinnerModelo1.setValue(0);


    jCheckBoxEXP.setSelected(false);
    jRadioButtonHavana.setSelected(false);
    jRadioButtonBambu.setSelected(false);
    jRadioButtonDonJulio.setSelected(false);
    jRadioButtonVodka.setSelected(false);
    jRadioButtonHennessy.setSelected(false);
    jRadioButtonBacardi.setSelected(false);
    jRadioButtonCorona6.setSelected(false);
    jRadioButtonModelo6.setSelected(false);
    jRadioButtonHeineken6.setSelected(false);
    jRadioButtonCorona1.setSelected(false);
    jRadioButtonModelo1.setSelected(false);
    jRadioButtonHeineken1.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jRadioButtonBacardiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBacardiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBacardiActionPerformed

    private void jCheckBoxEXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEXPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxEXPActionPerformed

    private void jRadioButtonDonJulioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDonJulioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDonJulioActionPerformed

    private void jRadioButtonVodkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVodkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonVodkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxEXP;
    private javax.swing.JCheckBox jCheckBoxTip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JRadioButton jRadioButtonBacardi;
    private javax.swing.JRadioButton jRadioButtonBambu;
    private javax.swing.JRadioButton jRadioButtonCorona1;
    private javax.swing.JRadioButton jRadioButtonCorona6;
    private javax.swing.JRadioButton jRadioButtonDonJulio;
    private javax.swing.JRadioButton jRadioButtonHavana;
    private javax.swing.JRadioButton jRadioButtonHeineken1;
    private javax.swing.JRadioButton jRadioButtonHeineken6;
    private javax.swing.JRadioButton jRadioButtonHennessy;
    private javax.swing.JRadioButton jRadioButtonModelo1;
    private javax.swing.JRadioButton jRadioButtonModelo6;
    private javax.swing.JRadioButton jRadioButtonVodka;
    private javax.swing.JSpinner jSpinnerBR1;
    private javax.swing.JSpinner jSpinnerBam3;
    private javax.swing.JSpinner jSpinnerCorona1;
    private javax.swing.JSpinner jSpinnerCorona6;
    private javax.swing.JSpinner jSpinnerDJ4;
    private javax.swing.JSpinner jSpinnerHC2;
    private javax.swing.JSpinner jSpinnerHeineken1;
    private javax.swing.JSpinner jSpinnerHeineken6;
    private javax.swing.JSpinner jSpinnerModelo1;
    private javax.swing.JSpinner jSpinnerModelo6;
    private javax.swing.JSpinner jSpinnerTH6;
    private javax.swing.JSpinner jSpinnerVS5;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldTip;
    // End of variables declaration//GEN-END:variables
}
